/*
This CSS file is automatically generated by the Theme Options panel (WP-Admin).
You should not manually edit it.
*/

/*
== ------------------------------------------------------------------- ==
== @@ Styling - Main
== ------------------------------------------------------------------- ==
*/

<?php if ( strtolower($data['styling-colors-main-background']) != '#ffffff' ) : ?>
.error404 #page_body {
	background-image:none
}
<?php endif; ?>

body,
a,
.sf-menu a, 
.invicta_post_navigation cite, 
.text_styles .invicta_partners .partner a, 
input[type="text"], 
input[type="input"], 
input[type="password"],
input[type="email"], 
input[type="number"], 
input[type="url"], 
input[type="tel"], 
input[type="search"], 
textarea, 
select,
input[type="text"]:focus, 
input[type="password"]:focus, 
input[type="email"]:focus, 
input[type="number"]:focus, 
input[type="url"]:focus, 
input[type="tel"]:focus, 
input[type="search"]:focus,
textarea:focus, 
.invicta_highlight, 
.invicta_heading .secondary, 
.invicta_heading .secondary strong,
.videos_loop_responsive li:before, 
.videos_loop .entry.active .video_thumbnail .playing:before, 
.page_header .header_main nav select, 
.page_header .header_meta, 
.invicta_world_map .label, 
.header_meta .language_switcher #lang_sel ul ul a {
	color:<?php echo $data['styling-colors-main-text']; ?>;
}

.invicta_photoslider .controller {
	background-color:<?php echo $data['styling-colors-main-text']; ?>;
	}

input[type="submit"],
.shipping_calculator button[type="submit"],  
.woocommerce button[name="calc_shipping"],
.checkout-button,
#submit, 
.invicta_button, 
.woocommerce .widget_price_filter .price_slider_amount .button, 
.woocommerce-page .widget_price_filter .price_slider_amount .button, 
.woocommerce .single_product_details .cart .button, 
.woocommerce-page .single_product_details .cart .button {
	background:<?php echo $data['styling-colors-main-text']; ?>;
	}

#invicta_top_arrow:hover {
	border-color:<?php echo $data['styling-colors-main-text']; ?>;
	}
	
.widget_categories li a { 
	border-left-color:<?php echo invicta_get_color_rgb( $data['styling-colors-main-text'] ); ?>; 
	border-left-color:<?php echo invicta_get_color_rgba( $data['styling-colors-main-text'], 0.70 ); ?>; 
	}
.widget_categories ul.children li a { 
	border-left-color:<?php echo invicta_get_color_rgb( $data['styling-colors-main-text'] ); ?>; 
	border-left-color:<?php echo invicta_get_color_rgba( $data['styling-colors-main-text'], 0.30 ); ?>; 
	}
.widget_categories ul.children li a:hover { 
	border-left-color:<?php echo invicta_get_color_rgb( $data['styling-colors-main-text'] ); ?>; 
	border-left-color:<?php echo invicta_get_color_rgba( $data['styling-colors-main-text'], 0.50 ); ?>; 
	background-color:<?php echo $data['styling-colors-main-background'] ?> !important; 
	}

#invicta_root,
.vc_text_separator div,
.portfolio_filters ul,
.invicta_boxed_layout #invicta_root, 
.invicta_iconbox a.icon:hover, 
input[type="text"]:focus, 
input[type="password"]:focus, 
input[type="email"]:focus, 
input[type="number"]:focus, 
input[type="url"]:focus, 
input[type="tel"]:focus, 
input[type="search"]:focus,
textarea:focus, 
.widget_categories li.current-cat a,
.widget_categories li a:hover, 
.widget_categories ul.children li a:hover, 
.invicta_heading_separator div, 
.visual_composer_invicta_styles .wpb_toggle_content, 
.visual_composer_invicta_styles .wpb_content_element.wpb_tabs .wpb_tour_tabs_wrapper .wpb_tab, 
.visual_composer_invicta_styles .wpb_content_element.wpb_tabs .wpb_tabs_nav li.ui-tabs-active, 
.visual_composer_invicta_styles .wpb_content_element.wpb_tabs .wpb_tabs_nav li.ui-tabs-active:hover, 
.visual_composer_invicta_styles .wpb_content_element.wpb_tour .wpb_tour_tabs_wrapper .wpb_tab, 
.visual_composer_invicta_styles .wpb_content_element.wpb_tour .wpb_tabs_nav li.ui-tabs-active, 
.visual_composer_invicta_styles .wpb_content_element.wpb_tour .wpb_tabs_nav li.ui-tabs-active:hover, 
.visual_composer_invicta_styles .wpb_content_element .wpb_accordion_wrapper .wpb_accordion_header.ui-state-active, 
.visual_composer_invicta_styles .wpb_content_element .wpb_accordion_wrapper .wpb_accordion_content,
.sf-menu ul li:hover, 
.sf-menu ul li.sfHover, 
.sf-menu ul .current_page_item, 
.sf-menu ul .current_page_parent, 
.sf-menu ul .current_page_ancestor, 
.widget_calendar #calendar_wrap tfoot td.pad, 
.invicta_person .thumbnail:before,
.header_meta .language_switcher #lang_sel ul ul a {
	background-color:<?php echo $data['styling-colors-main-background']; ?>;
	}		

.invicta_fixed_header .header_wrapper { 
	background-color:<?php echo invicta_get_color_rgb( $data['styling-colors-main-background'] ); ?>;
	background-color:<?php echo invicta_get_color_rgba( $data['styling-colors-main-background'], 0.85 ); ?>;
	}

.visual_composer_invicta_styles .wpb_content_element.wpb_tour .wpb_tabs_nav li.ui-tabs-active { 
	border-color:<?php echo $data['styling-colors-main-graphics']; ?>; 
	border-right-color:<?php echo $data['styling-colors-main-background']; ?>; 
	}
	
.visual_composer_invicta_styles .wpb_content_element.wpb_tabs .wpb_tabs_nav li.ui-tabs-active { 
	border-color:<?php echo $data['styling-colors-main-graphics']; ?>; 
	border-bottom-color:<?php echo $data['styling-colors-main-background']; ?>;
	}
	
.visual_composer_invicta_styles .wpb_content_element .wpb_accordion_wrapper .wpb_accordion_header { 
	border-color:<?php echo $data['styling-colors-main-graphics']; ?>; 
	border-left-color:<?php echo invicta_get_color_rgb( $data['styling-colors-main-graphics'] ); ?>; 
	border-left-color:<?php echo invicta_get_color_rgba( $data['styling-colors-main-graphics'], 0.80 ); ?>; 
	}
	
.visual_composer_invicta_styles .wpb_toggle { 
	border-color:<?php echo $data['styling-colors-main-graphics']; ?>; 
	border-left-color:<?php echo invicta_get_color_rgb( $data['styling-colors-main-graphics'] ); ?>;
	border-left-color:<?php echo invicta_get_color_rgba( $data['styling-colors-main-graphics'], 0.80 ); ?>;
	}

.photos_loop .entry .gallery_photos img.main, 
.photos_loop .entry .gallery_photos img.thumbnail {
	border-color:<?php echo $data['styling-colors-main-background']; ?>;
	}
	
.invicta_pagination .btn.current,
.invicta_pagination a.btn:hover {
	color:<?php echo $data['styling-colors-main-background']; ?>;
	}
	
input[type="submit"],
.shipping_calculator button[type="submit"],  
.woocommerce button[name="calc_shipping"],
.checkout-button,
#submit, 
.invicta_button, 
.woocommerce .widget_price_filter .price_slider_amount .button, 
.woocommerce-page .widget_price_filter .price_slider_amount .button, 
.woocommerce .single_product_details .cart .button, 
.woocommerce-page .single_product_details .cart .button { 
	color:<?php echo $data['styling-colors-main-background']; ?> !important; 
	}
	
.invicta_photoslider .controller span, 
.invicta_photoslider .controller a {
	color:<?php echo $data['styling-colors-main-background']; ?>;
	}

.page_header .title_area,
.page_header .header_main nav select,
select, 
.invicta_person.condensed,
.invicta_letter,
.page_footer .widgets, 
.text_styles tr:nth-child(odd), 
.blog_loop .sticky, 
.widget_categories ul.children li a, 
.visual_composer_invicta_styles .wpb_toggle, 
.visual_composer_invicta_styles .wpb_content_element.wpb_tabs .wpb_tabs_nav li, 
.visual_composer_invicta_styles .wpb_content_element.wpb_tour .wpb_tabs_nav li, .visual_composer_invicta_styles .wpb_content_element .wpb_accordion_wrapper .wpb_accordion_header,
.invicta_testimonial.style_1 .text, 
.blog_loop .entry .post_author, 
.comments_loop .entry .text .body .moderation, 
.page_header .header_meta,
.blog_loop .format-link, 
.blog_loop .format-aside, 
.blog_loop .format-quote, 
.blog_loop .format-status, 
.widget_categories.widget_photos_categories .tooltip, 
.widget_calendar #calendar_wrap thead th, 
.widget_categories li a, 
.invicta_iconbox .icon, 
input[type="text"], 
input[type="input"], 
input[type="password"],
input[type="email"], 
input[type="number"], 
input[type="url"], 
input[type="tel"], 
input[type="search"], 
textarea, 
.invicta_steps .step .icon,
.sf-menu ul li, 
.widget_calendar #calendar_wrap td.pad, 
.page_header .home_slideshow, 
.videos_loop .entry, 
#video_holder .loader, 
.text_styles blockquote, 
.video_page .video_details .entry, 
.portfolio_loop .entry .meta, 
.photos_loop .entry .meta, 
.videos_loop_list .entry .meta, 
.blog .blog_loop .entry, 
.archive .blog_loop .entry, 
.invicta_calltoaction, 
.header_meta .language_switcher #lang_sel ul ul a:hover { 
	background-color:<?php echo $data['styling-colors-main-background_alternate']; ?>; 
	}

.widget_categories .children li.current-cat > a, 
.widget_categories li.current-cat a,
.widget_categories li.current-cat > a { 
	background:<?php echo $data['styling-colors-main-background_alternate']; ?> !important; 
	}
	
.widget_categories li.current-cat > a {
	background-color:<?php echo $data['styling-colors-main-background']; ?> !important;
	}
	
.widget_categories.widget_photos_categories .tooltip:after, 
.invicta_testimonial.style_1 .text:after { 
	border-color:<?php echo $data['styling-colors-main-background_alternate']; ?> transparent; 
	}
	
.visual_composer_invicta_styles .wpb_content_element.wpb_tabs .wpb_tabs_nav li:hover, 
.visual_composer_invicta_styles .wpb_content_element.wpb_tour .wpb_tabs_nav li:hover {
	background:<?php echo invicta_get_color_variation( $data['styling-colors-main-background_alternate'], -8 ); ?>;
	}
	
.invicta_progressbars .progress_bar .bar {
	<?php if ( hexdec( $data['styling-colors-main-background'] ) < hexdec( $data['styling-colors-main-text'] ) ) : ?>
	background:<?php echo invicta_get_color_variation( $data['styling-colors-main-background_alternate'], 12 ); ?>;
	<?php else : ?>
	background:<?php echo invicta_get_color_variation( $data['styling-colors-main-background_alternate'], -10 ); ?>;
	<?php endif; ?>
	}
	
#invicta_top_arrow, 
#invicta_top_arrow:hover {
	<?php if ( hexdec( $data['styling-colors-main-background'] ) < hexdec( $data['styling-colors-main-text'] ) ) : ?>
	background:<?php echo invicta_get_color_variation( $data['styling-colors-main-background_alternate'], 12 ); ?>;
	<?php else : ?>
	background:<?php echo invicta_get_color_variation( $data['styling-colors-main-background_alternate'], -10 ); ?>;
	<?php endif; ?>
	}
	
.portfolio_filters ul:before { 
	<?php if ( hexdec( $data['styling-colors-main-background'] ) < hexdec( $data['styling-colors-main-text'] ) ) : ?>
	color:#FFF; 
	<?php else : ?>
	color:#000
	<?php endif; ?>
	}

h1, 
h2, 
h3, 
h4, 
h5, 
h6, 
.blog_loop .entry .post_extras .post_tags strong, 
.blog_loop .entry .post_author .text .author_name, 
.blog_loop .format-quote .before_meta, 
.blog_loop .format-status .before_meta, 
.comments_loop .entry .text .head .author, 
.comment_form label, 
.portfolio_details .entry .project_meta label, 
.invicta_heading .primary, 
.invicta_heading_separator div, 
.visual_composer_invicta_styles .vc_text_separator div, 
.visual_composer_invicta_styles .wpb_content_element.wpb_tabs .wpb_tabs_nav li.ui-tabs-active a, 
.visual_composer_invicta_styles .wpb_content_element.wpb_tour .wpb_tabs_nav li.ui-tabs-active a, 
.visual_composer_invicta_styles .wpb_content_element .wpb_accordion_wrapper .wpb_accordion_header.ui-state-active, 
.invicta_person .title, 
.invicta_twitterfeed .tweet .user, 
.wpcf7 .form_field label, 
.invicta_steps .step .name, 
.invicta_progressbars .progress_bar .legend .name, 
.invicta_testimonial .name, 
.invicta_iconbox .title {
	color:<?php echo $data['styling-colors-main-text_titles']; ?>;
}

.invicta_pagination .btn.current {
	background-color:<?php echo invicta_get_color_rgb( $data['styling-colors-main-text_titles'] ); ?>;
	background-color:<?php echo invicta_get_color_rgba( $data['styling-colors-main-text_titles'], 0.60 ); ?>;
	}

.invicta_iconbox .icon i, 
.invicta_steps .step .icon i {
	color:<?php echo invicta_get_color_rgb( $data['styling-colors-main-text_titles'] ); ?>;
	color:<?php echo invicta_get_color_rgba( $data['styling-colors-main-text_titles'], 0.60 ); ?>;
	}
	
.comments_loop .entry .text .head .date, 
.pings_loop .entry .date, 
.page_footer .socket, 
.page_footer .socket a, 
.invicta_post_navigation span,  
.invicta_progressbars .progress_bar .legend .value, 
.page_header .header_meta, 
.page_header .header_meta .social_links, 
.page_header .header_meta .tagline, 
.page_header .header_meta .searchbox, 
.header_meta .language_switcher, 
.blog_loop .entry .post_author .media .social_links, 
.searchform button, 
.invicta_twitterfeed .tweet .hash, 
.invicta_twitterfeed .tweet .tweet_date a, 
.invicta_breadcrumb .before, 
#invicta_top_arrow:hover, 
.error503 section .social_networks a, 
.blog_loop .format-link .post_title:after, 
.blog_loop .format-quote .before_meta:before, 
.portfolio_details .entry .project_skills ul li:before, 
.blog_loop_widget .entry .post_details .post_meta, 
.invicta_person .social a, 
.widget_categories.widget_photos_categories .tooltip, 
.videos_loop_responsive li .video_meta, 
.invicta_progressbars .progress_bar .bar .progress, 
.text_styles abbr, 
.text_styles acronym, 
.portfolio_loop .entry .meta .description, 
.photos_loop .entry .meta .description, 
.videos_loop_list .entry .meta .description {
	color:<?php echo $data['styling-colors-main-text_alternate']; ?>;
	}
	
.invicta_contacts li.email:after, 
.invicta_contacts li.map:after, 
.invicta_contacts li.url:after {
	color:<?php echo invicta_get_color_rgb( $data['styling-colors-main-text_alternate'] ); ?>;
	color:<?php echo invicta_get_color_rgba( $data['styling-colors-main-text_alternate'], 0.70 ); ?>;
	}
	
.page_header .header_meta .divider {
	color:<?php echo invicta_get_color_rgb( $data['styling-colors-main-text_alternate'] ); ?>;
	color:<?php echo invicta_get_color_rgba( $data['styling-colors-main-text_alternate'], 0.70 ); ?>;
	}
	
.widget_calendar #calendar_wrap tbody td a:hover, 
.wp-caption {
	border-color:<?php echo $data['styling-colors-main-text_alternate']; ?>;
	}
	
.invicta_contacts li.url:after { 
	color:<?php echo invicta_get_color_rgb( $data['styling-colors-main-text_alternate'] ); ?>; 
	color:<?php echo invicta_get_color_rgba( $data['styling-colors-main-text_alternate'], 0.60 ); ?>; 
	}

.page_header .title_area, 
.page_header .page_image, 
.search_loop .entry, 
.widget_categories ul,
.widget_categories li, 
.widget_calendar #calendar_wrap tbody td,
.visual_composer_invicta_styles .wpb_toggle_content, 
.visual_composer_invicta_styles .wpb_content_element.wpb_tabs .wpb_tour_tabs_wrapper .wpb_tab, 
.visual_composer_invicta_styles .wpb_content_element.wpb_tabs .wpb_tabs_nav li, 
.visual_composer_invicta_styles .wpb_content_element.wpb_tour .wpb_tour_tabs_wrapper .wpb_tab, 
.visual_composer_invicta_styles .wpb_content_element.wpb_tour .wpb_tabs_nav li, 
.visual_composer_invicta_styles .wpb_content_element .wpb_accordion_wrapper .wpb_accordion_content, 
.invicta_testimonial.style_1 .text,
.page_footer .widgets,
.invicta_heading_separator, 
.visual_composer_invicta_styles .vc_text_separator, 
.invicta_iconbox .icon, 
#invicta_top_arrow, 
.invicta_avatar, 
.comments_loop, 
.comments_loop .entry, 
.comments_loop .entry .text .body .moderation, 
.invicta_post_navigation .prev, 
.portfolio_details .invicta_post_navigation .next, 
input[type="text"], 
input[type="input"], 
input[type="password"],
input[type="email"], 
input[type="number"], 
input[type="url"], 
input[type="tel"], 
input[type="search"], 
textarea, 
select, 
.page_header .header_main nav select, 
.text_styles pre, 
.text_styles th, 
.text_styles td, 
.blog_loop .sticky, 
.visual_composer_invicta_styles .wpb_separator, 
.widget_categories.widget_photos_categories .tooltip, 
.invicta_steps .step .icon, 
.invicta_steps .step .icon .index, 
.widget_calendar #calendar_wrap thead th, 
.video_page .video_details .entry, 
.video_list_page .featured_video, 
.blog .blog_loop .entry, 
.archive .blog_loop .entry, 
.blog .blog_loop .format-status, 
.blog .blog_loop .format-aside, 
.blog .blog_loop .format-quote,
.blog .blog_loop .format-link, 
.blog .blog_loop .format-link,
.archive .blog_loop .format-status, 
.archive .blog_loop .format-aside, 
.archive .blog_loop .format-quote,
.archive .blog_loop .format-link, 
.archive .blog_loop .format-link, 
.portfolio_loop .entry, 
.photos_loop .entry, 
.videos_loop_list .entry, 
.invicta_fixed_header .header_wrapper.scrolled, 
.invicta_calltoaction { 
	border-color:<?php echo $data['styling-colors-main-graphics']; ?>;
}



.widget_categories.widget_photos_categories .tooltip:before, 
.invicta_testimonial.style_1 .text:before { border-color:<?php echo $data['styling-colors-main-graphics']; ?> transparent;  }

.page_header .header_meta { border-bottom-color:<?php echo $data['styling-colors-main-graphics']; ?>; }

.portfolio_filters { border-color:<?php echo $data['styling-colors-main-graphics']; ?>; }

.invicta_tags a { 
	background:<?php echo invicta_get_color_rgb( $data['styling-colors-main-graphics'] ); ?>;
	background:<?php echo invicta_get_color_rgba( $data['styling-colors-main-graphics'], 0.60 ); ?>;
	}
.invicta_pagination .btn { 
	background:<?php echo invicta_get_color_rgb( $data['styling-colors-main-graphics'] ); ?>; 
	background:<?php echo invicta_get_color_rgba( $data['styling-colors-main-graphics'], 0.70 ); ?>; 
	}

.invicta_steps .step .line { border-top-color:<?php echo $data['styling-colors-main-graphics']; ?>; }
.responsive .invicta_steps .step .line { border-left-color:<?php echo $data['styling-colors-main-graphics']; ?>; }

.sf-menu ul li { 
	<?php if ( hexdec( $data['styling-colors-main-background'] ) < hexdec( $data['styling-colors-main-graphics'] ) ) : ?>
	border-top-color:<?php echo $data['styling-colors-main-graphics']; ?>; 
	border-bottom-color:<?php echo $data['styling-colors-main-background']; ?>; 
	<?php else : ?>
	border-bottom-color:<?php echo $data['styling-colors-main-graphics']; ?>; 
	border-top-color:<?php echo $data['styling-colors-main-background']; ?>; 
	<?php endif; ?>
	}

<?php if ( strpos( $data['styling-background-main-pattern'], '0-none.png' ) === false ) : ?>
#invicta_root {
	background-image:url(<?php echo $data['styling-background-main-pattern']; ?>);
	background-attachment:scroll;
	background-repeat:repeat;
	background-position:center center;
}	
<?php endif; ?>

<?php if ( $data['styling-background-main-image'] ) : ?>
#invicta_root {
	background-image:url(<?php echo $data['styling-background-main-image']; ?>);
	background-attachment:<?php echo $data['styling-background-main-attachment']; ?>;
	background-repeat:<?php echo $data['styling-background-main-repeat']; ?>;
	background-position:<?php echo $data['styling-background-main-position']; ?>;
}
<?php endif; ?>	

.invicta_testimonial_carousel .background { color:<?php echo $data['styling-colors-main-text_alternate']; ?>; }
.invicta_testimonial_carousel .nav_arrows { background-color:<?php echo $data['styling-colors-main-graphics']; ?>; }
.invicta_testimonial_carousel .nav_bullets a { background-color:<?php echo $data['styling-colors-main-graphics']; ?>; }
.invicta_testimonial_carousel .nav_bullets a.current,
.invicta_testimonial_carousel .nav_bullets a.current:hover {
	background-color:<?php echo $data['styling-colors-main-text']; ?>;
	}
.invicta_testimonial_carousel .nav_bullets a:hover {
	background-color:<?php echo invicta_get_color_rgb( $data['styling-colors-main-text'] ); ?>; 
	background-color:<?php echo invicta_get_color_rgba( $data['styling-colors-main-text'], 0.50 ); ?>; 
	}
	
	
.invicta_world_map .label {
	<?php if ( hexdec( $data['styling-colors-main-background'] ) < hexdec( $data['styling-colors-main-text'] ) ) : ?>
	text-shadow:1px 1px 1px #000;
	<?php else : ?>
	text-shadow:1px 1px 1px #FFF;
	<?php endif; ?>
	}
	
/*
== ------------------------------------------------------------------- ==
== @@ Styling - Colors - Header
== ------------------------------------------------------------------- ==
*/

<?php if ( $data['styling-colors-header'] ) : ?>

	.page_header, 
	.header_meta .language_switcher #lang_sel ul ul a {
		background-color:<?php echo $data['styling-colors-header-background']; ?>; 
		}
		
	.invicta_fixed_header .header_wrapper { 
		background-color:<?php echo invicta_get_color_rgb( $data['styling-colors-header-background'] ); ?>;
		background-color:<?php echo invicta_get_color_rgba( $data['styling-colors-header-background'], 0.85 ); ?>;
		}
		
	.page_header .header_meta {
		background-color:<?php echo $data['styling-colors-header-background_alternate']; ?>;
		border-bottom-color:<?php echo $data['styling-colors-header-border']; ?>;
		}
		
	.page_header .header_main nav select,
	.page_header .home_slideshow, 
	.header_meta .language_switcher #lang_sel ul ul a:hover {
		background-color:<?php echo $data['styling-colors-header-background_alternate']; ?>;
		}
		
	.page_header .sf-menu a,
	.page_header .header_main nav select, 
	.header_meta .language_switcher #lang_sel ul ul a {
		color:<?php echo $data['styling-colors-header-text']; ?>;
		}
		
	.page_header .header_meta, 
	.page_header .header_meta .social_links, 
	.page_header .header_meta .tagline, 
	.page_header .header_meta .searchbox, 
	.page_header .searchform button {
		color:<?php echo $data['styling-colors-header-text_alternate']; ?>;
		}
		
	.page_header .header_meta .searchbox .divider {
		color:<?php echo invicta_get_color_rgb( $data['styling-colors-header-text_alternate'] ); ?>;
		color:<?php echo invicta_get_color_rgba( $data['styling-colors-header-text_alternate'], 0.70 ); ?>;
		}
		
	.page_header .header_main nav select {
		border-color:<?php echo $data['styling-colors-header-border']; ?>;
		}

	.page_header input[type="text"], 
	.page_header input[type="password"], 
	.page_header input[type="email"], 
	.page_header input[type="number"], 
	.page_header input[type="url"], 
	.page_header input[type="tel"], 
	.page_header input[type="search"],
	.page_header textarea {
		color:<?php echo $data['styling-colors-header-text_alternate']; ?>;
		}
				
	.page_header input[type="text"]:focus, 
	.page_header input[type="password"]:focus, 
	.page_header input[type="email"]:focus, 
	.page_header input[type="number"]:focus, 
	.page_header input[type="url"]:focus, 
	.page_header input[type="tel"]:focus, 
	.page_header input[type="search"]:focus,
	.page_header textarea:focus {
		color:<?php echo $data['styling-colors-header-text']; ?>;
		}
		
	.page_header .header_meta {
		border-top-color:<?php echo $data['styling-colors-header-top_border_line']; ?>;
		}
		
	<?php if ( strpos( $data['styling-background-header-pattern'], '0-none.png' ) === false ) : ?>
	.page_header {
		background-image:url(<?php echo $data['styling-background-header-pattern']; ?>);
		background-attachment:scroll;
		background-repeat:repeat;
		background-position:center center;
	}
	.invicta_fixed_header .header_wrapper { 
		background-color:transparent;
		background-image:url(<?php echo $data['styling-background-header-pattern']; ?>);
		background-attachment:scroll;
		background-repeat:repeat;
		background-position:center center;
		}
	<?php endif; ?>
	
	<?php if ( $data['styling-background-header-image'] ) : ?>
	.page_header {
		background-image:url(<?php echo $data['styling-background-header-image']; ?>);
		background-attachment:<?php echo $data['styling-background-header-attachment']; ?>;
		background-repeat:<?php echo $data['styling-background-header-repeat']; ?>;
		background-position:<?php echo $data['styling-background-header-position']; ?>;
	}
	.invicta_fixed_header .header_wrapper { 
		background-color:transparent;
		background-image:url(<?php echo $data['styling-background-header-image']; ?>);
		background-attachment:<?php echo $data['styling-background-header-attachment']; ?>;
		background-repeat:<?php echo $data['styling-background-header-repeat']; ?>;
		background-position:<?php echo $data['styling-background-header-position']; ?>;
	}
	<?php endif; ?>	
	
<?php endif; ?>

/*
== ------------------------------------------------------------------- ==
== @@ Styling - Colors - Title Area
== ------------------------------------------------------------------- ==
*/

<?php if ( $data['styling-colors-title'] ) : ?>

	.page_header .title_area {
		background-color:<?php echo $data['styling-colors-title-background']; ?>; 
		}
		
	.page_header .title_area {
		border-color:<?php echo $data['styling-colors-title-border']; ?>; 
		}
		
	.page_header .title_area h1 {
		color:<?php echo $data['styling-colors-title-text']; ?>; 
		}
		
	.page_header .title_area, 
	.page_header .title_area a {
		color:<?php echo $data['styling-colors-title-text_alternate']; ?>; 
		}
		
	<?php if ( strpos( $data['styling-background-title-pattern'], '0-none.png' ) === false ) : ?>
	.page_header .title_area {
		background-image:url(<?php echo $data['styling-background-title-pattern']; ?>);
		background-attachment:scroll;
		background-repeat:repeat;
		background-position:center center;
	}	
	<?php endif; ?>
	
	<?php if ( $data['styling-background-title-image'] ) : ?>
	.page_header .title_area {
		background-image:url(<?php echo $data['styling-background-title-image']; ?>);
		background-attachment:<?php echo $data['styling-background-title-attachment']; ?>;
		background-repeat:<?php echo $data['styling-background-title-repeat']; ?>;
		background-position:<?php echo $data['styling-background-title-position']; ?>;
	}
	<?php endif; ?>	
		
<?php endif; ?>	

/*
== ------------------------------------------------------------------- ==
== @@ Styling - Colors - Footer
== ------------------------------------------------------------------- ==
*/

<?php if ( $data['styling-colors-footer'] ) : ?>

	.page_footer .widgets {
		background-color:<?php echo $data['styling-colors-footer-background']; ?>;
		border-color:<?php echo $data['styling-colors-footer-border']; ?>;
		}
	
	.page_footer .widgets, 
	.page_footer .widgets a {
		color:<?php echo $data['styling-colors-footer-text']; ?>;
		}
		
	.page_footer .widgets,
	.page_footer .widgets a,
	.page_footer .widgets .text_styles .invicta_partners .partner a, 
	.page_footer .widgets input[type="text"]:focus, 
	.page_footer .widgets input[type="password"]:focus, 
	.page_footer .widgets input[type="email"]:focus, 
	.page_footer .widgets input[type="number"]:focus, 
	.page_footer .widgets input[type="url"]:focus, 
	.page_footer .widgets input[type="tel"]:focus, 
	.page_footer .widgets input[type="search"]:focus,
	.page_footer .widgets textarea:focus, 
	.page_footer .widgets .invicta_highlight, 
	.page_footer .widgets .invicta_heading .secondary, 
	.page_footer .widgets .invicta_heading .secondary strong, 
	.page_footer .widgets .videos_loop_responsive li:before, 
	.page_footer .widgets .videos_loop .entry.active .video_thumbnail .playing:before {
		color:<?php echo $data['styling-colors-footer-text']; ?>;
	}
	
	.page_footer .widgets input[type="submit"],
	.page_footer .widgets #submit, 
	.page_footer .widgets .invicta_button,
	.woocommerce .page_footer .widget_price_filter .price_slider_amount .button, 
	.woocommerce-page .page_footer .widget_price_filter .price_slider_amount .button {
		background:<?php echo $data['styling-colors-footer-text']; ?>;
		}
		
	.page_footer .widgets .widget_categories li a { 
		border-left-color:<?php echo invicta_get_color_rgb( $data['styling-colors-footer-text'] ); ?>; 
		border-left-color:<?php echo invicta_get_color_rgba( $data['styling-colors-footer-text'], 0.70 ); ?>; 
		}
	.page_footer .widgets .widget_categories ul.children li a { 
		border-left-color:<?php echo invicta_get_color_rgb( $data['styling-colors-footer-text'] ); ?>; 
		border-left-color:<?php echo invicta_get_color_rgba( $data['styling-colors-footer-text'], 0.30 ); ?>; 
		}
	.page_footer .widgets .widget_categories ul.children li a:hover	{ 
		border-left-color:<?php echo invicta_get_color_rgb( $data['styling-colors-footer-text'] ); ?>; 
		border-left-color:<?php echo invicta_get_color_rgba( $data['styling-colors-footer-text'], 0.50 ); ?>; 
		}
	
	.page_footer .widgets .vc_text_separator div,
	.page_footer .widgets .portfolio_filters ul,
	.page_footer .widgets .invicta_iconbox a.icon:hover, 
	.page_footer .widgets input[type="text"]:focus, 
	.page_footer .widgets input[type="password"]:focus, 
	.page_footer .widgets input[type="email"]:focus, 
	.page_footer .widgets input[type="number"]:focus, 
	.page_footer .widgets input[type="url"]:focus, 
	.page_footer .widgets input[type="tel"]:focus, 
	.page_footer .widgets input[type="search"]:focus,
	.page_footer .widgets textarea:focus, 
	.page_footer .widgets .invicta_heading_separator div, 
	.page_footer .widgets .widget_categories ul.children li a:hover, 
	.visual_composer_invicta_styles .page_footer .widgets .wpb_toggle_content, 
	.visual_composer_invicta_styles .page_footer .widgets .wpb_content_element.wpb_tabs .wpb_tour_tabs_wrapper .wpb_tab, 
	.visual_composer_invicta_styles .page_footer .widgets .wpb_content_element.wpb_tabs .wpb_tabs_nav li.ui-tabs-active, 
	.visual_composer_invicta_styles .page_footer .widgets .wpb_content_element.wpb_tabs .wpb_tabs_nav li.ui-tabs-active:hover, 
	.visual_composer_invicta_styles .page_footer .widgets .wpb_content_element.wpb_tour .wpb_tour_tabs_wrapper .wpb_tab, 
	.visual_composer_invicta_styles .page_footer .widgets .wpb_content_element.wpb_tour .wpb_tabs_nav li.ui-tabs-active, 
	.visual_composer_invicta_styles .page_footer .widgets .wpb_content_element.wpb_tour .wpb_tabs_nav li.ui-tabs-active:hover, 
	.visual_composer_invicta_styles .page_footer .widgets .wpb_content_element .wpb_accordion_wrapper .wpb_accordion_header.ui-state-active, 
	.visual_composer_invicta_styles .page_footer .widgets .wpb_content_element .wpb_accordion_wrapper .wpb_accordion_content,
	.widget_calendar #calendar_wrap tfoot td.pad {
		background-color:<?php echo $data['styling-colors-footer-background']; ?>;
		}
	
	.visual_composer_invicta_styles .page_footer .widgets .wpb_content_element.wpb_tour .wpb_tabs_nav li.ui-tabs-active { 
		border-color:<?php echo $data['styling-colors-footer-graphics']; ?>; 
		border-right-color:<?php echo $data['styling-colors-footer-background']; ?>; 
		}
		
	.visual_composer_invicta_styles .page_footer .widgets .wpb_content_element.wpb_tabs .wpb_tabs_nav li.ui-tabs-active { 
		border-color:<?php echo $data['styling-colors-footer-graphics']; ?>; 
		border-bottom-color:<?php echo $data['styling-colors-footer-background']; ?>;
		}
		
	.visual_composer_invicta_styles .page_footer .widgets .wpb_content_element .wpb_accordion_wrapper .wpb_accordion_header { 
		border-color:<?php echo $data['styling-colors-footer-graphics']; ?>; 
		border-left-color:<?php echo invicta_get_color_rgb( $data['styling-colors-footer-graphics'] ); ?>; 
		border-left-color:<?php echo invicta_get_color_rgba( $data['styling-colors-footer-graphics'], 0.80 ); ?>; 
		}
		
	.visual_composer_invicta_styles .page_footer .widgets .wpb_toggle { 
		border-color:<?php echo $data['styling-colors-footer-graphics']; ?>; 
		border-left-color:<?php echo invicta_get_color_rgb( $data['styling-colors-footer-graphics'] ); ?>; 
		border-left-color:<?php echo invicta_get_color_rgba( $data['styling-colors-footer-graphics'], 0.80 ); ?>; 
		}
			
	.page_footer .widgets input[type="submit"],
	.page_footer .widgets #submit, 
	.page_footer .widgets .invicta_button, 
	.woocommerce .page_footer .widget_price_filter .price_slider_amount .button, 
	.woocommerce-page .page_footer .widget_price_filter .price_slider_amount .button { 
		color:<?php echo $data['styling-colors-footer-background']; ?> !important; 
		}
	
	.page_footer .widgets select, 
	.page_footer .widgets .invicta_person.condensed,
	.page_footer .widgets .invicta_letter,
	.page_footer .widgets .text_styles tr:nth-child(odd), 
	.page_footer .widgets .blog_loop .sticky, 
	.page_footer .widgets .widget_categories li a:hover,
	.page_footer .widgets .widget_categories ul.children li a, 
	.visual_composer_invicta_styles .page_footer .widgets .wpb_toggle, 
	.visual_composer_invicta_styles .page_footer .widgets .wpb_content_element.wpb_tabs .wpb_tabs_nav li, 
	.visual_composer_invicta_styles .page_footer .widgets .wpb_content_element.wpb_tour .wpb_tabs_nav li, 
	.visual_composer_invicta_styles .wpb_content_element .wpb_accordion_wrapper .wpb_accordion_header,
	.page_footer .widgets .invicta_testimonial.style_1 .text, 
	.page_footer .widgets .widget_categories.widget_photos_categories .tooltip, 
	.page_footer .widgets .widget_calendar #calendar_wrap thead th, 
	.page_footer .widgets .widget_categories li a, 
	.page_footer .widgets .invicta_iconbox .icon, 
	.page_footer .widgets input[type="text"], 
	.page_footer .widgets input[type="input"], 
	.page_footer .widgets input[type="password"],
	.page_footer .widgets input[type="email"], 
	.page_footer .widgets input[type="number"], 
	.page_footer .widgets input[type="url"], 
	.page_footer .widgets input[type="tel"], 
	.page_footer .widgets input[type="search"], 
	.page_footer .widgets textarea, 
	.page_footer .widgets .invicta_steps .step .icon,
	.page_footer .widgets .widget_calendar #calendar_wrap td.pad, 
	.page_footer .widgets .text_styles blockquote { 
		background-color:<?php echo $data['styling-colors-footer-background_alternate']; ?>; 
		}
	
	.page_footer .widgets .widget_categories .children li.current-cat > a, 
	.page_footer .widgets .widget_categories li.current-cat a,
	.page_footer .widgets .widget_categories li.current-cat > a { 
		background:<?php echo $data['styling-colors-footer-background_alternate']; ?> !important; 
		}
		
	.page_footer .widgets .widget_categories.widget_photos_categories .tooltip:after, 
	.page_footer .widgets .invicta_testimonial.style_1 .text:after { 
		border-color:<?php echo $data['styling-colors-footer-background_alternate']; ?> transparent; 
		}
		
	.visual_composer_invicta_styles .page_footer .widgets .wpb_content_element.wpb_tabs .wpb_tabs_nav li:hover, 
	.visual_composer_invicta_styles .page_footer .widgets .wpb_content_element.wpb_tour .wpb_tabs_nav li:hover {
		background:<?php echo invicta_get_color_variation( $data['styling-colors-footer-background_alternate'], -8 ); ?>;
		}
		
	.page_footer .widgets .invicta_progressbars .progress_bar .bar {
		<?php if ( hexdec( $data['styling-colors-footer-background'] ) < hexdec( $data['styling-colors-footer-text'] ) ) : ?>
		background:<?php echo invicta_get_color_variation( $data['styling-colors-footer-background_alternate'], 12 ); ?>;
		<?php else : ?>
		background:<?php echo invicta_get_color_variation( $data['styling-colors-footer-background_alternate'], -10 ); ?>;
		<?php endif; ?>
		}
	
	.page_footer .widgets h1, 
	.page_footer .widgets h2, 
	.page_footer .widgets h3, 
	.page_footer .widgets h4, 
	.page_footer .widgets h5, 
	.page_footer .widgets h6, 
	.page_footer .widgets .invicta_heading .primary, 
	.page_footer .widgets .invicta_heading_separator div, 
	.visual_composer_invicta_styles .page_footer .widgets .vc_text_separator div, 
	.visual_composer_invicta_styles .page_footer .widgets .wpb_content_element.wpb_tabs .wpb_tabs_nav li.ui-tabs-active a, 
	.visual_composer_invicta_styles .page_footer .widgets .wpb_content_element.wpb_tour .wpb_tabs_nav li.ui-tabs-active a, 
	.visual_composer_invicta_styles .page_footer .widgets .wpb_content_element .wpb_accordion_wrapper .wpb_accordion_header.ui-state-active, 
	.page_footer .widgets .invicta_person .title, 
	.page_footer .widgets .invicta_twitterfeed .tweet .user, 
	.page_footer .widgets .wpcf7 .form_field label, 
	.page_footer .widgets .invicta_steps .step .name, 
	.page_footer .widgets .invicta_progressbars .progress_bar .legend .name, 
	.page_footer .widgets .invicta_testimonial .name, 
	.page_footer .widgets .invicta_iconbox .title {
		color:<?php echo $data['styling-colors-footer-text_titles']; ?>;
	}
	
	.page_footer .widgets .invicta_iconbox .icon i, 
	.page_footer .widgets .invicta_steps .step .icon i {
		color:<?php echo invicta_get_color_rgb( $data['styling-colors-footer-text_titles'] ); ?>;
		color:<?php echo invicta_get_color_rgba( $data['styling-colors-footer-text_titles'], 0.60 ); ?>;
		}
		
	.page_footer .widgets input[type="text"], 
	.page_footer .widgets input[type="input"], 
	.page_footer .widgets input[type="password"],
	.page_footer .widgets input[type="email"], 
	.page_footer .widgets input[type="number"], 
	.page_footer .widgets input[type="url"], 
	.page_footer .widgets input[type="tel"], 
	.page_footer .widgets input[type="search"], 
	.page_footer .widgets textarea, 
	.page_footer .widgets select, 
	.page_footer .widgets .invicta_progressbars .progress_bar .legend .value, 
	.page_footer .widgets .searchform button, 
	.page_footer .widgets .invicta_twitterfeed .tweet .hash, 
	.page_footer .widgets .invicta_twitterfeed .tweet .tweet_date a, 
	.page_footer .widgets .invicta_breadcrumb .before, 
	.page_footer .widgets .blog_loop_widget .entry .post_details .post_meta, 
	.page_footer .widgets .invicta_person .social a, 
	.page_footer .widgets .widget_categories.widget_photos_categories .tooltip, 
	.page_footer .widgets .invicta_progressbars .progress_bar .bar .progress, 
	.page_footer .widgets .text_styles abbr, 
	.page_footer .widgets .text_styles acronym {
		color:<?php echo $data['styling-colors-footer-text_alternate']; ?>;
		}
		
	.page_footer .widgets .invicta_contacts li.email:after, 
	.page_footer .widgets .invicta_contacts li.map:after, 
	.page_footer .widgets .invicta_contacts li.url:after {
		color:<?php echo invicta_get_color_rgb( $data['styling-colors-footer-text_alternate'] ); ?>;
		color:<?php echo invicta_get_color_rgba( $data['styling-colors-footer-text_alternate'], 0.70 ); ?>;
		}
		
	.page_footer .widgets .widget_calendar #calendar_wrap tbody td a:hover, 
	.page_footer .widgets .wp-caption {
		border-color:<?php echo $data['styling-colors-footer-text_alternate']; ?>;
		}
		
	.page_footer .widgets .invicta_contacts li.url:after { 
		color:<?php echo invicta_get_color_rgb( $data['styling-colors-footer-text_alternate'] ); ?>;
		color:<?php echo invicta_get_color_rgba( $data['styling-colors-footer-text_alternate'], 0.60 ); ?>;
		}
	
	.page_footer .widgets .widget_categories ul,
	.page_footer .widgets .widget_categories li, 
	.page_footer .widgets .widget_calendar #calendar_wrap tbody td,
	.visual_composer_invicta_styles .page_footer .widgets .wpb_toggle_content, 
	.visual_composer_invicta_styles .page_footer .widgets .wpb_content_element.wpb_tabs .wpb_tour_tabs_wrapper .wpb_tab, 
	.visual_composer_invicta_styles .page_footer .widgets .wpb_content_element.wpb_tabs .wpb_tabs_nav li, 
	.visual_composer_invicta_styles .page_footer .widgets .wpb_content_element.wpb_tour .wpb_tour_tabs_wrapper .wpb_tab, 
	.visual_composer_invicta_styles .page_footer .widgets .wpb_content_element.wpb_tour .wpb_tabs_nav li, 
	.visual_composer_invicta_styles .page_footer .widgets .wpb_content_element .wpb_accordion_wrapper .wpb_accordion_content, 
	.page_footer .widgets .invicta_testimonial.style_1 .text,
	.page_footer .widgets .invicta_heading_separator, 
	.visual_composer_invicta_styles .page_footer .widgets .vc_text_separator, 
	.page_footer .widgets .invicta_iconbox .icon, 
	.page_footer .widgets .invicta_avatar, 
	.page_footer .widgets input[type="text"], 
	.page_footer .widgets input[type="input"], 
	.page_footer .widgets input[type="password"],
	.page_footer .widgets input[type="email"], 
	.page_footer .widgets input[type="number"], 
	.page_footer .widgets input[type="url"], 
	.page_footer .widgets input[type="tel"], 
	.page_footer .widgets input[type="search"], 
	.page_footer .widgets textarea, 
	.page_footer .widgets select, 
	.page_footer .widgets .text_styles pre, 
	.page_footer .widgets .text_styles th, 
	.page_footer .widgets .text_styles td, 
	.visual_composer_invicta_styles .page_footer .widgets .wpb_separator, 
	.page_footer .widgets .invicta_steps .step .icon, 
	.page_footer .widgets .invicta_steps .step .icon .index, 
	.page_footer .widgets .widget_calendar #calendar_wrap thead th { 
		border-color:<?php echo $data['styling-colors-footer-graphics']; ?>;
	}
	
	.page_footer .widgets .invicta_testimonial.style_1 .text:before { border-color:<?php echo $data['styling-colors-footer-graphics']; ?> transparent;  }
	.page_footer .widgets .invicta_tags a { 
		background:<?php echo invicta_get_color_rgb( $data['styling-colors-footer-graphics'] ); ?>; 
		background:<?php echo invicta_get_color_rgba( $data['styling-colors-footer-graphics'], 0.60 ); ?>; 
		}
	.page_footer .widgets .invicta_steps .step .line { border-top-color:<?php echo $data['styling-colors-footer-graphics']; ?>; }
	.responsive .page_footer .widgets .invicta_steps .step .line { border-left-color:<?php echo $data['styling-colors-footer-graphics']; ?>; }
	
	<?php if ( strpos( $data['styling-background-footer-pattern'], '0-none.png' ) === false ) : ?>
	.page_footer .widgets {
		background-image:url(<?php echo $data['styling-background-footer-pattern']; ?>);
		background-attachment:scroll;
		background-repeat:repeat;
		background-position:center center;
	}	
	<?php endif; ?>
	
	<?php if ( $data['styling-background-footer-image'] ) : ?>
	.page_footer .widgets {
		background-image:url(<?php echo $data['styling-background-footer-image']; ?>);
		background-attachment:<?php echo $data['styling-background-footer-attachment']; ?>;
		background-repeat:<?php echo $data['styling-background-footer-repeat']; ?>;
		background-position:<?php echo $data['styling-background-footer-position']; ?>;
	}
	<?php endif; ?>	

		
<?php endif; ?>	

/*
== ------------------------------------------------------------------- ==
== @@ Styling - Colors - Socket
== ------------------------------------------------------------------- ==
*/

<?php if ( $data['styling-colors-socket'] ) : ?>

	.page_footer .socket {
		background-color:<?php echo $data['styling-colors-socket-background']; ?>; 
		color:<?php echo $data['styling-colors-socket-text']; ?>;
		}
		
	.page_footer .socket {
		border-bottom-color:<?php echo $data['styling-colors-socket-bottom_border_line']; ?> !important;
		}
		
	.page_footer .socket a {
		color:<?php echo $data['styling-colors-socket-text']; ?>;
		}
		
	.page_footer .socket a:hover {
		color:<?php echo $data['styling-colors-socket-text_alternate']; ?>;
		}
		
<?php endif; ?>

/*
== ------------------------------------------------------------------- ==
== @@ Styling - Colors - Menu
== ------------------------------------------------------------------- ==
*/

<?php if ( $data['styling-colors-menu'] ) : ?>

	.page_header .sf-menu a {
		color:<?php echo $data['styling-colors-menu-text']; ?>;
		}
		
	.page_header .sf-menu ul li {
		background-color:<?php echo $data['styling-colors-menu-background']; ?>;
		}
		
	.page_header .header_main nav select {
		background-color:<?php echo $data['styling-colors-menu-background']; ?>;
		}
		
	.page_header .sf-menu ul li:hover,
	.page_header .sf-menu ul li.sfHover, 
	.page_header .sf-menu ul .current_page_item,
	.page_header .sf-menu ul .current_page_parent,
	.page_header .sf-menu ul .current_page_ancestor {
		background-color:<?php echo $data['styling-colors-menu-background_alternate']; ?>;
		}
		
	.page_header .sf-menu ul li {
		border-bottom-color:<?php echo $data['styling-colors-menu-divider_bottom']; ?>;
		border-top-color:<?php echo $data['styling-colors-menu-divider_top']; ?>;
		}
		
	.page_header .sf-menu a:hover, 
	.page_header .sf-menu > .current_page_ancestor > a
	.page_header .sf-menu > li:hover > a,
	.page_header .sf-menu > li.sfHover > a,
	.page_header .sf-menu > .current_page_item > a,
	.page_header .sf-menu > .current_page_parent > a,
	.page_header .sf-menu > .current_page_ancestor > a {
		color:<?php echo $data['styling-colors-menu-accent']; ?>;
		}
		
	.page_header .sf-arrows ul li > .sf-with-ul:focus:after,
	.page_header .sf-arrows ul li:hover > .sf-with-ul:after,
	.page_header .sf-arrows ul .sfHover > .sf-with-ul:after {
		border-left-color:<?php echo $data['styling-colors-menu-accent']; ?>;
		}
		
	.page_header .sf-menu ul {
		border-color:<?php echo $data['styling-colors-menu-accent']; ?>;
		}
	.page_header .sf-menu ul .current_page_item > a, 
	.page_header .sf-menu ul .current_page_parent > a, 
	.page_header .sf-menu ul .current_page_ancestor > a {
		color:<?php echo $data['styling-colors-menu-accent']; ?>;
		}
		
	.page_header .sf-arrows ul .sf-with-ul:after {
		border-left-color:<?php echo $data['styling-colors-menu-arrows']; ?>;
		}
	
<?php endif; ?>		

/*
== ------------------------------------------------------------------- ==
== @@ Styling - Colors - Hover Effect
== ------------------------------------------------------------------- ==
*/

<?php if ( $data['styling-colors-hover_effect'] ) : ?>
		
	#invicta_root .invicta_hover_effect .mask {	
		background-color:<?php echo $data['styling-colors-hover_effect-background']; ?>;
		background-color:<?php echo invicta_get_color_rgba( $data['styling-colors-hover_effect-background'], 0.70 ); ?>;
		}
		
	#invicta_root .invicta_hover_effect .caption .title, 
	#invicta_root .invicta_hover_effect .caption .description {
		color:<?php echo $data['styling-colors-hover_effect-text']; ?>;
		}
		
	.invicta_steps .step:hover .icon {	
		background-color:<?php echo $data['styling-colors-hover_effect-background']; ?>;
		}
		
	.invicta_steps .step:hover .icon i {
		color:<?php echo $data['styling-colors-hover_effect-text']; ?>;
		}
	
<?php endif; ?>	

/*
== ------------------------------------------------------------------- ==
== @@ Styling - Colors - Others
== ------------------------------------------------------------------- ==
*/

.page_header .home_slideshow {
	border-top-color:<?php echo $data['styling-colors-other-front_page_slideshow_border']; ?>;
	border-bottom-color:<?php echo $data['styling-colors-other-front_page_slideshow_border']; ?>;
	}


/*
== ------------------------------------------------------------------- ==
== @@ Accent Colors
== ------------------------------------------------------------------- ==
*/

::selection {
	background:<?php echo $data['colors-accent']; ?>;
	color:#FFF;
	}	
::-moz-selection {
	background:<?php echo $data['colors-accent']; ?>;
	color:#FFF;
	}
	
a:hover {
	color:<?php echo $data['colors-accent']; ?>;
	}

.text_styles a {
	color:<?php echo $data['colors-accent']; ?>;
	}
	
.inherit-color,
.inherit-color-on_children >* {
	color:inherit;
	}

.accentcolor-text, 
.accentcolor-text-on_children >*,
.accentcolor-text-on_hover:hover, 
.accentcolor-text-on_children-on_hover >*:hover {
	color:<?php echo $data['colors-accent']; ?> !important;
	}

.accentcolor-border, 
.accentcolor-border-on_children >*, 
.accentcolor-border-on_hover:hover, 
.accentcolor-border-on_children-on_hover >*:hover { 
	border-color:<?php echo $data['colors-accent']; ?> !important; 
	}

.accentcolor-background, 
.accentcolor-background-on_children >*, 
.accentcolor-background-on_hover:hover, 
.accentcolor-background-on_children-on_hover >*:hover {
	background-color:<?php echo $data['colors-accent']; ?> !important;
	}


.sf-menu > li:hover > a,
.sf-menu > li.sfHover > a,
.sf-menu > .current_page_item > a,
.sf-menu > .current_page_parent > a,
.sf-menu > .current_page_ancestor > a {
	color:<?php echo $data['colors-accent']; ?>;
	}
	
.sf-arrows ul li > .sf-with-ul:focus:after,
.sf-arrows ul li:hover > .sf-with-ul:after,
.sf-arrows ul .sfHover > .sf-with-ul:after {
	border-left-color:<?php echo $data['colors-accent']; ?>;
	}
	
.sf-menu ul {
	border-color:<?php echo $data['colors-accent']; ?>;
	}
.sf-menu ul .current_page_item > a, 
.sf-menu ul .current_page_parent > a, 
.sf-menu ul .current_page_ancestor > a {
	color:<?php echo $data['colors-accent']; ?>;
	}

input[type="submit"]:hover, 
.shipping_calculator button[type="submit"]:hover, 
.woocommerce button[name="calc_shipping"]:hover,
.checkout-button:hover, 
#submit:hover, 
.invicta_button:hover, 
.blog_loop .entry .more-link:hover, 
.woocommerce .widget_price_filter .price_slider_amount .button:hover, 
.woocommerce-page .widget_price_filter .price_slider_amount .button:hover, 
.woocommerce .single_product_details .cart .button:hover, 
.woocommerce-page .single_product_details .cart .button:hover {
	background-color:<?php echo $data['colors-accent']; ?>;
	}
	
.widget ul li:before, 
.blog_loop_widget .entry.no_thumbnail .post_details:before {
	color:<?php echo $data['colors-accent']; ?>;
	}
	
.widget_categories li.current-cat a, 
.widget_categories ul.children li.current-cat a {
	border-color:<?php echo $data['colors-accent']; ?>;
	}
	
.widget_calendar #calendar_wrap td#today, 
.widget_calendar #calendar_wrap tbody td a {
	color:<?php echo $data['colors-accent']; ?>;
	}
	
.widget_pages .current_page_item a,	
.widget_nav_menu .current_page_item a {
	color:<?php echo $data['colors-accent']; ?>;
	}
	
.widget_recent_comments a {
	color:<?php echo $data['colors-accent']; ?>;
	}
	
.invicta_canvas .mejs-controls .mejs-time-rail .mejs-time-current {
	background-color:<?php echo $data['colors-accent']; ?>;
	}
	
.visual_composer_invicta_styles .wpb_toggle.wpb_toggle_title_active {
	border-left-color:<?php echo $data['colors-accent']; ?>;
	}
	
.visual_composer_invicta_styles .vc_toggle.vc_toggle_active .vc_toggle_title {
	border-left-color:<?php echo $data['colors-accent']; ?>;
	}
	
.visual_composer_invicta_styles .wpb_content_element.wpb_tabs .wpb_tabs_nav li.ui-tabs-active {
	border-top-color:<?php echo $data['colors-accent']; ?>;
	}
	
.visual_composer_invicta_styles .wpb_content_element.wpb_tour .wpb_tabs_nav li.ui-tabs-active {
	border-left-color:<?php echo $data['colors-accent']; ?>;
	}
	
.visual_composer_invicta_styles .wpb_content_element .wpb_accordion_wrapper .wpb_accordion_header.ui-state-active,
.visual_composer_invicta_styles .wpb_content_element .wpb_accordion_wrapper .wpb_accordion_content {
	border-left-color:<?php echo $data['colors-accent']; ?>;
	}
	
.portfolio_filters .active {
	color:<?php echo $data['colors-accent']; ?>;
	}
	
.text_styles .widget_pages a:hover, 
.text_styles .widget_nav_menu a:hover {
	color:<?php echo $data['colors-accent']; ?>;
	}
	
.text_styles ul > li:before {
	color:<?php echo $data['colors-accent']; ?>;
	}
	
.invicta_heading .primary strong { 
	color:<?php echo $data['colors-accent']; ?>;
	}
	
.videos_loop_responsive li.active a, 
.videos_loop_responsive li.active:before {
	color:<?php echo $data['colors-accent']; ?>;
	}
	
.invicta_hover_effect .mask {	
	background-color:<?php echo $data['colors-accent']; ?>;
	background-color:<?php echo invicta_get_color_rgba( $data['colors-accent'], 0.70 ); ?>;
	}
	
.invicta_steps .step:hover .icon {
	background-color:<?php echo $data['colors-accent']; ?>;	
	}
	
.invicta_world_map .marker {
	background-color:<?php echo $data['colors-accent']; ?>;	
	-webkit-box-shadow:0px 0px 1px 1px <?php echo $data['colors-accent']; ?>;
	   -moz-box-shadow:0px 0px 1px 1px <?php echo $data['colors-accent']; ?>;
	     -o-box-shadow:0px 0px 1px 1px <?php echo $data['colors-accent']; ?>;
	        box-shadow:0px 0px 1px 1px <?php echo $data['colors-accent']; ?>;
	}	
	
.invicta_photoslider .thumbnails_pane .thumbnails .thumb.current {
	border-color:<?php echo $data['colors-accent']; ?>;	
	}
	
.portfolio_loop .entry:hover, 
.photos_loop .entry:hover, 
.videos_loop_list .entry:hover {
	border-color:<?php echo $data['colors-accent']; ?>;	
	}
	
.blog .blog_loop .entry:hover,
.archive .blog_loop .entry:hover {
	border-color:<?php echo $data['colors-accent']; ?>;	
	}
	
/*
== ------------------------------------------------------------------- ==
== @@ Styling
== ------------------------------------------------------------------- ==
*/

.invicta_boxed_layout .body_background {
	<?php if ( $data['styling-boxed_layout'] ) : ?>
	background-color:<?php echo $data['styling-boxed_layout-background_color']; ?>;
	<?php endif; ?>
	<?php if ( $data['styling-boxed_layout-background_pattern'] ) : ?>
		<?php if ( strpos( $data['styling-boxed_layout-background_pattern'], '0-none.png' ) !== false ) : ?>
	background-image:none;
		<?php else : ?>
	background-image:url(<?php echo $data['styling-boxed_layout-background_pattern']; ?>);
		<?php endif; ?>
	<?php endif; ?>
	background-attachment:fixed;
	background-repeat:repeat;
	background-position:center center;
}

<?php if ( $data['styling-boxed_layout-background_image'] ) : ?>
.invicta_boxed_layout .body_background {
	background-image:url(<?php echo $data['styling-boxed_layout-background_image']; ?>);
	background-attachment:<?php echo $data['styling-boxed_layout-background_attachment']; ?>;
	<?php if ( $data['styling-boxed_layout-background_repeat'] != 'fullscreen' ) : ?>
	background-repeat:<?php echo $data['styling-boxed_layout-background_repeat']; ?>;
	<?php endif; ?>	
	background-position:<?php echo $data['styling-boxed_layout-background_position']; ?>;
}

<?php if ( $data['styling-boxed_layout-background_repeat'] == 'fullscreen' ) : ?>
.invicta_boxed_layout .body_background { 
	background-attachment:fixed;
	background-size:cover;
	background-position:center center;
}
<?php endif; ?>

<?php endif; ?>




<?php if ( $data['styling-boxed_layout-drop_shadow'] ) : ?>
.invicta_boxed_layout #invicta_root {
	-webkit-box-shadow: 0 0 5px 0px rgba(0, 0, 0, 0.5);
	   -moz-box-shadow: 0 0 5px 0px rgba(0, 0, 0, 0.5);
	     -o-box-shadow: 0 0 5px 0px rgba(0, 0, 0, 0.5);
	        box-shadow: 0 0 5px 0px rgba(0, 0, 0, 0.5);
}
<?php endif; ?>

<?php if ( $data['styling-boxed_layout-vertical_margin'] && $data['styling-boxed_layout-vertical_margin'] > 0 ) : ?> 
.invicta_boxed_layout .body_background { 
	padding-top:<?php echo $data['styling-boxed_layout-vertical_margin'] ?>px;
	padding-bottom:<?php echo $data['styling-boxed_layout-vertical_margin'] ?>px;
}

@media only screen and (min-width:1000px) and (max-width:1060px) {
	.invicta_boxed_layout .body_background { padding-top:0 !important; padding-bottom:0 !important; }
}
@media only screen and (min-width:768px) and (max-width:783px) {
	.invicta_boxed_layout .body_background { padding-top:0 !important; padding-bottom:0 !important; }
}
@media only screen and (min-width:480px) and (max-width:528px) {
	.invicta_boxed_layout .body_background { padding-top:0 !important; padding-bottom:0 !important; }
}
@media only screen and (max-width:368px) {
	.invicta_boxed_layout .body_background { padding-top:0 !important; padding-bottom:0 !important; }
}

<?php endif; ?>
	
/*
== ------------------------------------------------------------------- ==
== @@ Typography
== ------------------------------------------------------------------- ==
*/

/* font family */

<?php if ( $data['typography-body-family'] != 'none' && $data['typography-body-family'] != 'google' ) : ?>
body,
input,
select,
textarea {
	font-family:"<?php echo $data['typography-body-family']; ?>";
	}
<?php endif; ?>	

<?php if ( $data['typography-headings-family'] != 'none' && $data['typography-headings-family'] != 'google' ) : ?>
h1, 
h2, 
h3, 
h4, 
h5, 
h6 {
	font-family:"<?php echo $data['typography-headings-family']; ?>";
	}
<?php endif; ?>

<?php if ( $data['typography-menu-family'] != 'none' && $data['typography-menu-family'] != 'google' ) : ?>	
#main_menu {
	font-family:"<?php echo $data['typography-menu-family']; ?>";
	}
<?php endif; ?>

/* uppercases */

<?php if ( $data['typography-headings-uppercase-widget_titles'] ) : ?>	
.widget .widget_title {
	text-transform:uppercase;
	} 
.portfolio_filters {
	text-transform:uppercase;
	font-size:0.9em;
	} 
<?php endif; ?>

<?php if ( $data['typography-headings-uppercase-page_title'] ) : ?>	
.page_header .title_area {
	text-transform:uppercase;
	} 
<?php endif; ?>

<?php if ( $data['typography-headings-uppercase-content_titles'] ) : ?>	
.main_column h1, 
.main_column h2, 
.main_column h3, 
.main_column h4, 
.main_column h5, 
.main_column h6 {
	text-transform:uppercase;
	} 
<?php endif; ?>

<?php if ( $data['typography-menu-uppercase-root'] ) : ?>	
.sf-menu > li > a {
	text-transform:uppercase;
	} 
<?php endif; ?>

<?php if ( $data['typography-menu-uppercase-children'] ) : ?>	
.sf-menu > li li a {
	text-transform:uppercase;
	} 
<?php endif; ?>


/* font sizes */

body { font-size:<?php echo $data['typography-body-size']; ?>px; }
.page_header .title_area h1 { font-size:<?php echo ( $data['typography-headings-size-page_title'] / 100); ?>em; }
h1 { font-size:<?php echo ( $data['typography-headings-size-h1'] / 100); ?>em; }
h2 { font-size:<?php echo ( $data['typography-headings-size-h2'] / 100); ?>em; }
h3 { font-size:<?php echo ( $data['typography-headings-size-h3'] / 100); ?>em; }
h4 { font-size:<?php echo ( $data['typography-headings-size-h4'] / 100); ?>em; }
h5 { font-size:<?php echo ( $data['typography-headings-size-h5'] / 100); ?>em; }
h6 { font-size:<?php echo ( $data['typography-headings-size-h6'] / 100); ?>em; }
.sf-menu { font-size:<?php echo ( $data['typography-menu-size'] / 100); ?>em; }


/*
== ------------------------------------------------------------------- ==
== @@ WooCommerce
== ------------------------------------------------------------------- ==
*/

.woocommerce .single_product_details p.price, 
.woocommerce-page .single_product_details p.price, 
.woocommerce .single_product_details .product_meta a, 
.woocommerce-page .single_product_details .product_meta a, 
.woocommerce .single_product_details .variations_form .single_variation, 
.woocommerce-page .single_product_details .variations_form .single_variation, 
.woocommerce .side_column .widget_shopping_cart_content .total strong, 
.woocommerce .form-row label .required,
.woocommerce-page .form-row label .required, 
.woocommerce table.shop_table tr.total th, 
.woocommerce table.shop_table tr.total, 
.woocommerce .cart-collaterals h2 a:hover, 
.woocommerce .cart-collaterals .cart_totals .total th, 
.woocommerce .cart-collaterals .cart_totals .total td, 
.woocommerce .product_sorting .sort_param ul li:before, 
.woocommerce .product_sorting .sort_param ul li.current_param a { 
	color:<?php echo $data['colors-accent']; ?>;
	}
	
.invicta_canvas .woocommerce-info:before, 
.woocommerce span.onsale,
.woocommerce-page span.onsale {
	background-color:<?php echo $data['colors-accent']; ?>;
	}
	
.woocommerce.widget_layered_nav li.chosen a {
	background-color:<?php echo $data['colors-accent']; ?>;
	color:#FFF;
	}
	
.woocommerce .woocommerce-message, 
.woocommerce .woocommerce-info {
	border-left-color:<?php echo $data['colors-accent']; ?>;
	}
	
.woocommerce ul.products li.product .product_entry,
.woocommerce-page ul.products li.product .product_entry {
	border-color:<?php echo $data['styling-colors-main-graphics']; ?>;
	}
	
.woocommerce .ul.products li.product .product_meta, 
.woocommerce-page ul.products li.product .product_meta, 
.woocommerce .ul.products li.product .product_buttons, 
.woocommerce-page ul.products li.product .product_buttons {
	background-color:<?php echo $data['styling-colors-main-background_alternate']; ?>; 
	}
	
.woocommerce .star-rating:before, 
.woocommerce-page .star-rating:before, 
.woocommerce ul.products li.product .price del, 
.woocommerce-page ul.products li.product .price del, 
.woocommerce .ul.products li.product .button-mini-delimiter, 
.woocommerce-page ul.products li.product .button-mini-delimiter, 
.woocommerce .single_product_details p.price del, 
.woocommerce-page .single_product_details p.price del, 
.woocommerce .single_product_details .variations_form .single_variation del, 
.woocommerce-page .single_product_details .variations_form .single_variation del, 
.woocommerce #reviews #comments ol.commentlist li .comment-text .meta, 
.woocommerce-page #reviews #comments ol.commentlist li .comment-text .meta, 
.woocommerce #reviews #comments ol.commentlist li .comment-text .meta, 
.woocommerce-page #reviews #comments ol.commentlist li .comment-text .meta, 
.woocommerce.widget ul.product_list_widget li .amount, 
.woocommerce.widget_product_search #searchsubmit, 
.woocommerce form.checkout .chzn-container-single .chzn-single {
	color:<?php echo $data['styling-colors-main-text_alternate']; ?>;
	}
	
.woocommerce ul.products li.product .price, 
.woocommerce-page ul.products li.product .price {
	color:<?php echo $data['styling-colors-main-text']; ?>;
	}
	
.woocommerce .cart .quantity input.minus, 
.woocommerce-page .cart .quantity input.minus, 
.woocommerce .cart .quantity input.plus, 
.woocommerce-page .cart .quantity input.plus { 
	border-color:<?php echo $data['styling-colors-main-graphics']; ?>;
	background-color:<?php echo $data['styling-colors-main-background_alternate']; ?>;
	color:<?php echo $data['styling-colors-main-text_alternate']; ?>;
	}
	
.woocommerce .cart .quantity .qty, 
.woocommerce-page .cart .quantity .qty { 
	border-color:<?php echo $data['styling-colors-main-graphics']; ?>;
	background-color:<?php echo $data['styling-colors-main-background']; ?>;
	color:<?php echo $data['styling-colors-main-text_alternate']; ?>;
	}
	
.woocommerce .single_product_details .variations_form, 
.woocommerce-page .single_product_details .variations_form, 
.woocommerce div.product .woocommerce-tabs ul.tabs li, 
.woocommerce-page div.product .woocommerce-tabs ul.tabs li, 
.woocommerce #reviews #comments ol.commentlist, 
.woocommerce-page #reviews #comments ol.commentlist, 
.woocommerce #reviews #comments ol.commentlist li, 
.woocommerce-page #reviews #comments ol.commentlist li, 
.woocommerce.widget ul.product_list_widget li, 
.woocommerce .side_column .widget_shopping_cart_content .buttons, 
.woocommerce .addresses.col2-set .col-1, 
.woocommerce .addresses.col2-set .col-2,
.woocommerce-page .addresses.col2-set .col-1, 
.woocommerce-page .addresses.col2-set .col-2, 
.woocommerce table.shop_table .remove, 
.woocommerce .woocommerce-message, 
.woocommerce .woocommerce-info, 
.woocommerce form.login, 
.woocommerce_header_cart .widget_shopping_cart_content li, 
.woocommerce_header_cart .widget_shopping_cart_content li:first-child, 
.woocommerce_header_cart .widget_shopping_cart_content p.buttons, 
.woocommerce_header_cart .added_to_cart_notification, 
.woocommerce form.checkout .chzn-container-single .chzn-single, 
.woocommerce-checkout .form-row .chzn-container .chzn-drop, 
.woocommerce ul.payment_methods, 
.woocommerce ul.payment_methods li, 
.woocommerce .order_details, 
.woocommerce .order_details li, 
.woocommerce .product_sorting .sort_param > li > span, 
.woocommerce .product_sorting .sort_param > li > a, 
.woocommerce .product_sorting .sort_param ul, 
.invicta_canvas .woocommerce-info {
	border-color:<?php echo $data['styling-colors-main-graphics']; ?>;
	}
	
.woocommerce div.product .woocommerce-tabs ul.tabs li, 
.woocommerce-page div.product .woocommerce-tabs ul.tabs li, 
.woocommerce .addresses.col2-set .col-1, 
.woocommerce .addresses.col2-set .col-2,
.woocommerce-page .addresses.col2-set .col-1, 
.woocommerce-page .addresses.col2-set .col-2, 
.woocommerce .woocommerce-message, 
.woocommerce .woocommerce-info, 
.woocommerce form.login, 
.woocommerce_header_cart .widget_shopping_cart_content li:hover, 
.woocommerce_header_cart .widget_shopping_cart_content p.buttons, 
.woocommerce_header_cart .added_to_cart_notification, 
.woocommerce form.checkout .chzn-container-single .chzn-single, 
.woocommerce .order_details, 
.woocommerce .product_sorting .sort_param > li > span, 
.woocommerce .product_sorting .sort_param > li > a {
	background-color:<?php echo $data['styling-colors-main-background_alternate']; ?>;
	}
	
.woocommerce div.product .woocommerce-tabs ul.tabs li.active, 
.woocommerce-page div.product .woocommerce-tabs ul.tabs li.active {
	border-top-color:<?php echo $data['colors-accent']; ?>;
	border-bottom-color:<?php echo $data['styling-colors-main-background']; ?>;
	background-color:<?php echo $data['styling-colors-main-background']; ?>;
	}
	
.woocommerce div.product .woocommerce-tabs ul.tabs li:hover, 
.woocommerce-page div.product .woocommerce-tabs ul.tabs li:hover {
	background-color:<?php echo invicta_get_color_variation( $data['styling-colors-main-background_alternate'], -8 ); ?>	
	}
	
.woocommerce div.product .woocommerce-tabs ul.tabs li.active:hover, 
.woocommerce-page div.product .woocommerce-tabs ul.tabs li.active:hover, 
.woocommerce table.shop_table .remove, 
.woocommerce_header_cart .widget_shopping_cart_content li, 
.woocommerce .product_sorting .sort_param ul { 
	background-color:<?php echo $data['styling-colors-main-background']; ?>;
	}
	
.woocommerce div.product .woocommerce-tabs ul.tabs li.active a, 
.woocommerce-page div.product .woocommerce-tabs ul.tabs li.active a, 
.woocommerce #reviews #comments ol.commentlist li .comment-text .meta strong, 
.woocommerce-page #reviews #comments ol.commentlist li .comment-text .meta strong, 
.woocommerce table.shop_table th, 
.woocommerce_header_cart .widget_shopping_cart_content li a, 
.woocommerce_header_cart .added_to_cart_notification .product_name strong, 
.woocommerce ul.payment_methods li label { 
	color:<?php echo $data['styling-colors-main-text_titles']; ?>;
	}
	
.woocommerce div.proudct .woocommerce-tabs .panel, 
.woocommerce-page div.product .woocommerce-tabs .panel { 
	background-color:<?php echo $data['styling-colors-main-background']; ?>;
	border-color:<?php echo $data['styling-colors-main-graphics']; ?>;
	}
	
.woocommerce .widget_price_filter .price_slider_wrapper .ui-widget-content, 
.woocommerce-page .widget_price_filter .price_slider_wrapper .ui-widget-content { 
	background:<?php echo $data['styling-colors-main-text_alternate']; ?>;
	}
	
.woocommerce .widget_price_filter .ui-slider .ui-slider-range,
.woocommerce-page .widget_price_filter .ui-slider .ui-slider-range, 
.woocommerce .widget_price_filter .ui-slider .ui-slider-handle, 
.woocommerce-page .widget_price_filter .ui-slider .ui-slider-handle {
	background-color:<?php echo $data['styling-colors-main-graphics']; ?>;
	}
	
.woocommerce .widget_price_filter .ui-slider .ui-slider-handle, 
.woocommerce-page .widget_price_filter .ui-slider .ui-slider-handle { 
	border-color:<?php echo $data['styling-colors-footer-graphics']; ?>;
	}
	
.woocommerce.widget_price_filter .ui-slider.hovered .ui-slider-range {
	background-color:<?php echo $data['colors-accent']; ?>;
	}
	
.woocommerce.widget_price_filter .ui-slider.hovered .ui-slider-handle {
	background-color:<?php echo $data['colors-accent']; ?>;
	border-color:<?php echo $data['colors-accent']; ?>;
	}
	
.woocommerce table.shop_table td.actions .coupon .input-text { 
	border-color:<?php echo $data['styling-colors-main-graphics']; ?>;
	background-color:<?php echo $data['styling-colors-main-background']; ?>;
	color:<?php echo $data['styling-colors-main-text_alternate']; ?>;
	}

@media only screen and (max-width:480px) { 
	.responsive table.shop_table, 
	.responsive table.shop_table .product-name, 
	.responsive table.shop_table .actions { 
		border-color:<?php echo $data['styling-colors-main-graphics']; ?>;
		}
}

.woocommerce_header_cart .added_to_cart_notification:after { 
	border-color:<?php echo $data['styling-colors-main-background_alternate']; ?> transparent; 
	}
	
.woocommerce_header_cart .added_to_cart_notification:before { 
	border-color:<?php echo $data['styling-colors-main-graphics']; ?> transparent;
	}
	
/*
== ------------------------------------------------------------------- ==
== @@ Logo Spacing
== ------------------------------------------------------------------- ==
*/	

<?php if ( isset( $data['header-logo_spacing'] ) ) : ?>	
.page_header .logo img {
	padding: <?php echo $data['header-logo_spacing'] ?>px 0;
}
<?php endif; ?>

/*
== ------------------------------------------------------------------- ==
== @@ Custom CSS Code
== ------------------------------------------------------------------- ==
*/

<?php 
if ( $data['general-custom_css'] ) {
	echo $data['general-custom_css'];
}
?>
